# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sebastian Wunderlich
title: M.Sc. Blockchain & Distributed Ledger Technologies
email: s.wunderlich[at]hotmail.com
website: swunderlich.xyz

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username:  sproogen
instagram_username: jameswgrant
linkedin_username: jameswgrant

# Additional icon links
additional_links:
- title: ENS Address
  icon: fab fa-ethereum
  url: <your_ens_address>

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Sebastian, a blockchain and distributed ledger technology specialist. I hold a Master's in Blockchain & DLT from the University of Applied Sciences Mittweida, where I graduated with honors.

  I am passionate about the transformational potential of blockchain technology. My aim is to leverage my technical skills and economics background to drive innovation in this rapidly evolving space.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by digging holes and making game-changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Company is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Applied Sciences Mittweida
        caption: 2020 - 2023
        sub_title: M.Sc. Blockchain & Distributed Ledger Technologies
        quote: >
          The two year program in Blockchain & Distributed Ledger Technology is the first two year program world wide focusing on Distributed Ledger technologies.
        description: | # this will include new lines to allow paragraphs
          The program focuses on the Bitcoin and Ethereum blockchains. The curriculum offers comprehensive insights into these transformative technologies. An in depth understanding of Ethereum is given with an introduction to Solidity.
          To deepen my Comouter Science knowledge, I spent a semester abroad at James Cook University in Singapore, further expanding my horizon.
          Beyond technology, the program nurtured an innovative spirit, equipping graduates like myself with entrepreneurial skills for real-world impact.
          
          
      - layout: left
        title: Free University of Berlin,
        caption: 2015 - 2019
        sub_title: B.Sc. Economics
        quote: >
          Founded in 1948, the Free University of Berlin (Freie Universität Berlin) stands as a renowned institution in Germany and beyond.
        description: | # this will include new lines to allow paragraphs
          With a strong commitment to academic excellence and interdisciplinary learning, the university offers a dynamic environment for students pursuing various fields of study. The B.Sc. in Economics program at the Free University of Berlin is designed to provide students with a comprehensive understanding of economic principles, theories, and applications. Renowned for its rigorous curriculum and diverse faculty, the university equips graduates with the analytical skills and knowledge needed to excel in the dynamic world of economics and beyond

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in economics and computer science some of my other interests and hobbies are:
      - surfing
      - snowboarding
      - diving

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
