# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sebastian Wunderlich
title: PhD Student at University of Technology Sydney (UTS)
email: s.wunderlich[at]hotmail.com


# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 
github_username: SebCode37
linkedin_username: "sebastian-w-b3156582"


# Additional icon links
additional_links:
- title: ENS Address
  icon: fab fa-ethereum
  url: "https://www.google.com/search?q=swunderlich.eth"

- title: PGP Key
  icon: fas fa-key
  url: https://raw.githubusercontent.com/l0wbird1337/l0wbird1337.github.io/main/pubkey.txt

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Sebastian, \
  a distributed ledger technology expert currently pursuing my PhD at the University of Technology Sydney (UTS), funded by the Digital
  Finance Cooperative Research Centre (DFCRC). \
  I hold a Master’s in Blockchain &amp; DLT from the University of Applied Science Mittweida and a Bachelor's in Economics from the Free University of Berlin.
                         
  I am passionate about the transformational potential of technology. My aim is to leverage my technical skills and economics background to drive innovation in this rapidly
  evolving space.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Deloitte Blockchain Institute
        link: www2.deloitte.com
        sub_title: Consultant Internship
        caption: April 2022 - September 2022
        quote: >
          Worked alongside the business and the tech team
        description: | # this will include new lines to allow paragraphs
            My role as a Technical Consultant had me diving deep into different blockchain areas. I explored Hyperledger Aries and ACA-Py and worked with JavaScript and TypeScript. My scope ranged from CBDC to DeFi.
            
#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
      - layout: left
        title: Blockchain Competence Center Mittweida (BCCM)
        link: blockchain.hs-mittweida.de
        sub_title: Researcher
        caption: June 2021 - August 2021
        quote: >
          Study on tokenization and the potential economic impact of Web3
        description: | # this will include new lines to allow paragraphs
            At BCCM, my efforts took me towards a fascinating study on tokenization and Web3. Supported by the Economic Council and the German Parliament, I led research, interviewing industry giants like BCG, IBM, ITSA and more.

# - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
      - layout: left
        title: Blockchain Competence Center Mittweida (BCCM)
        link: blockchain.hs-mittweida.de
        sub_title: Researcher L2 Technologies
        caption: December 2020 - February 2021
        quote: >
          Research on Layer 2 Technologies with a focus on Ethereum Ecosystem
        description: | # this will include new lines to allow paragraphs
            Research on Layer 2 Solutions in the Distributed Ledger Space. Focused on Ethereum and Bitcoin. Lightning, Rollups, State channels. Created the most comprehensive list of Layer 2 Projects in 2021.

#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
      - layout: left
        title: German Parliament (Deutscher Bundestag)
        link: bundestag.de
        sub_title: Digital Policy Analyst
        caption: May 2019 - August 2019
        quote: >
          Pushing digitization 
        description: | # this will include new lines to allow paragraphs
            Focused on Distributed Ledger Technologies, Artificial Intelligence, Platform Economics and Belt and Road Initiative. Book published: Neustaat- Politik und Staat mussen sich ändern. Pitched ideas in front of members of parliament.



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Applied Sciences Mittweida
        caption: 2020 - 2023
        sub_title: M.Sc. Blockchain & Distributed Ledger Technologies
        quote: >
          The program is the world's first two-year curriculum dedicated to Distributed Ledger Technologies.
        description: | # this will include new lines to allow paragraphs
          The program focuses on the Bitcoin and Ethereum blockchain. The curriculum offers comprehensive insights into these transformative technologies. An in depth understanding of Ethereum is given with an introduction to Solidity.
          To deepen my Computer Science knowledge, I spent a semester abroad at James Cook University in Singapore.
          
          
          
      - layout: left
        title: Free University of Berlin,
        caption: 2015 - 2019
        sub_title: B.Sc. Economics
        quote: >
          Founded in 1948, the Free University of Berlin (Freie Universität Berlin) stands as a renowned institution in Germany.
        description: | # this will include new lines to allow paragraphs
          With a strong commitment to academic excellence and interdisciplinary learning, the university offers a dynamic environment for students. During my studies I spent one semester in Athens, Greece at the Athens University of Economics and Business and one semester in Kuala Lumpur at Monash University Malaysia.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
    <div style="text-align: center;">
      Alongside my interests in economics and computer science, some of my other interests and hobbies are surfing, snowboarding, diving, and traveling.
    </div>
    
      Alongside my interests in economics and computer science some of my other interests and hobbies are surfing, snowboarding, diving and traveling.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag


